name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

variables:
- template: blueprint.pipeline.variables.yaml

trigger:
  branches:
    include:
      - develop
      - staging
      - release
      - main
  paths:
    include:
      - Blueprints/New-Project

stages:
- stage: Build
  jobs:
  - template: blueprint.pipeline.build.yaml

- stage: Validate
  jobs:
  - template: blueprint.pipeline.validate.yaml

- stage: Publish
  jobs:
  - template: blueprint.pipeline.publish.yaml